### ISSUE TITLE
Release 0.6.1 is missing Cargo.lock

### ISSUE THREAD

**Issue by raimue** [mesalock-linux/mesalink#10]
While release 0.6.0 still included Cargo.lock, it was [removed](6c4c1603c5fe6354f4baff0b7cfe6d48e443c194) for release 0.6.1. This is a problem for packaging mesalink, as it is unknown which version of crates are supposed to be used. Without the exact versions of crates, it is also impossible to reproduce the binaries you publish with a release.

Upstream [advises](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) not to check in Cargo.lock for libraries. However, I do not think this applies to mesalink, as the build result for distribution is a "classic" library as a binary file and not as a rust crate (which is basically a source code tarball).

Please release `Cargo.lock` with the source code.

**Comment by ymjing** [comment]
Yes. MesaLink is a binary, not a Rust "library". We'll add Cargo.lock back in the next release.
