### ISSUE TITLE
Support Cipher Suite TLS_RSA_WITH_AES_128_CBC_SHA for TLS 1.2 compatability

### ISSUE THREAD

**Issue by DavidNiehues** [mesalock-linux/mesalink#11]
Hello mesalink team,

As I was evaluating your library, I stumbled upon the missing support of the cipher suite TLS_RSA_WITH_AES_128_CBC_SHA which is mandatory as of the [TLS 1.2 specification section 9](https://tools.ietf.org/html/rfc5246#section-9).

How to reproduce:

1.  Checkout mesalink v.0.6.1 from github
2. Compile it as explained in README.md
3. Start the server in examples/server/server as explained in README.md
4. Disable all cipher suites except for TLS_RSA_WITH_AES_128_CBC_SHA in your browser. (e.g. [as explained here for firefox](https://support.mozilla.org/de/questions/1119007))
5. Try to connect to the server.

For example Firefox will show that no supported cipher suite was found. Capturing the traffic with wireshark shows that the mesalink server sends an alert.
Enabeling more cipher suites again allows to do successfull handshakes.

**Comment by ymjing** [comment]
AES in CBC mode is vulnerable to [padding oracle attacks](https://blog.cloudflare.com/padding-oracles-and-the-decline-of-cbc-mode-ciphersuites/). In addtion, MesaLink (and the underlying `rustls`) utilizes `ring` for crypto; and`ring` does not support any non-AEAD ciphers such as AES in CBC mode. So we do not have any plan to support non-AEAD ciphers.

We do have a plan to implement RSA key exchange for compatibility reasons. Actually missing that would not cause a significant problem for Alexa top-1M sites in our tests. So probably you will find `TLS_RSA_WITH_AES_256_GCM_SHA256` soon in the upcoming releases.

**Comment by DavidNiehues** [comment]
Thanks for the quick reply.

Security is a good reason to not implement that cipher suite. However, the TLS 1.2 standard still states the cipher suite as mandatory, even though it is a bad idea.

Could you then please maintain a list of supported readily available list of supported cipher suites? At least that would have saved me a some time and could help others figure out if your library is an option for them.
