### ISSUE TITLE
Cannot install mesalink under CentOS6

### ISSUE THREAD

**Issue by haima2** [mesalock-linux/mesalink#13]
System:CentOS6.9 x86_64
The error message is as follows：
```logs
aclocal: --install should copy macros in the directory indicated by the
aclocal: first -I option, but no -I was supplied.
```

How should I solve it? I did not find a solution on the network
Thank you.

**Comment by ymjing** [comment]
The error message explains exactly the problem. Please replace the following line in `autogen.sh`
```
aclocal --install || exit 1
```
with
```
aclocal -I m4 --install || exit 1
```

The `-I` switch tells aclocal where to look for the m4 macros. For MesaLink, this is the `m4` directory.

CentOS 6.8 is too old to build MesaLink and its dependencies. For example, you may find the assembler complain about unsupported CPU instructions.

**Comment by haima2** [comment]
Thank you, I upgraded the compiler version myself, try it later, thank you for your reply.

**Comment by ymjing** [comment]
You may want to try CMake to build/install MesaLink 1.0.
