### ISSUE TITLE
autoreconf: automake failed with exit status: 1

### ISSUE THREAD

**Issue by lea4n** [mesalock-linux/mesalink#20]
./autogen.sh --enable-examples

automake: warnings are treated as errors
examples/0rtt_client/include.am:3: warning: compiling 'examples/0rtt_client/0rtt_client.c' in subdir requires 'AM_PROG_CC_C_O' in 'configure.ac'
Makefile.am:24:   'examples/include.am' included from here
examples/include.am:2:   'examples/0rtt_client/include.am' included from here

**Comment by ymjing** [comment]
I understand autotools can be painful to setup. Please use CMake to build MesaLink 1.0.
