### ISSUE TITLE
support Windows?

### ISSUE THREAD

**Issue by crusty-dave** [mesalock-linux/mesalink#23]
From the build instructions:

> MesaLink currently supports Linux, Android and macOS. We will introduce support for other platforms in future releases.

When is Windows support expected?

Note that rust-native-tls supports the following:

> Specifically, this crate uses SChannel on Windows (via the schannel crate), Secure Transport on OSX (via the security-framework crate), and OpenSSL (via the openssl crate) on all other platforms.

**Comment by ymjing** [comment]
@crusty-dave MesaLink's SSL_set_fd() API uses `std::os::unix::io::FromRawFd`, which is only available on Linux/Unix. It wouldn't be too hard to add `std::os::windows::io::FromRawHandle` for Windows support. Are you interested in creating a pull request?

**Comment by crusty-dave** [comment]
@kevinis Sorry, I wouldn't have time.  I would probably stick with rust_native_tls or rustls instead.

**Comment by ymjing** [comment]
@crusty-dave If your project is in Rust, rustls would be a better choice because MesaLink only provides C FFI APIs.

**Comment by sagebind** [comment]
I'd be interested in helping out to push MesaLink over the finish line, if it isn't there already now with #33. I have a Windows machine for working on.

**Comment by ymjing** [comment]
@sagebind  It would be great if you would like to help!

The CI pipelines on Azure have been testing native and cross MesaLink builds for Windows MSVC/Mingw; but the cargo and bogo tests only run on x86_64_linux for now.
