### ISSUE TITLE
Problem with cmake rust detection

### ISSUE THREAD

**Issue by Chaz6** [mesalock-linux/mesalink#24]
```
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Cargo Home: /home/chaz/.cargo
-- Rust Compiler Version: rustc 1.33.0
CMake Error at CMakeLists.txt:26 (message):
  Rust is too old, please install at least 1.31 to support the Rust 2018
  edition
```

The host is running linux 3.10.0-957.5.1.el7.x86_64.

**Comment by ymjing** [comment]
Probably a bug in [FindRust.cmake](https://github.com/mesalock-linux/mesalink/blob/master/cmake/FindRust.cmake). Let me look into this...

**Comment by ymjing** [comment]
The "Rust Compiler Version" detected by cmake should be "1.33.0", not "rustc 1.33.0".

@Chaz6 could you share with me the result if you clean the build directory and re-run "cmake .."?

**Comment by ymjing** [comment]
@Chaz6 would you mind testing PR #25 ?

**Comment by ymjing** [comment]
PR #25 merged. I'm closing this issue.

**Comment by Chaz6** [comment]
Confirmed fixed, thanks!
