### ISSUE TITLE
how to use mesalink with tokio(tokio-tls)

### ISSUE THREAD

**Issue by SSebo** [mesalock-linux/mesalink#32]
Is there any doc or tutorial ?  Thanks a lot.

**Comment by ymjing** [comment]
The lateste doc is at https://mesalock-linux.github.io/mesalink-doc/doc/mesalink/index.html

Although we have a `mesalink` crate on crates-io, MeasLink is more like `openssl-sys`. The SSL type does not implement AsyncRead or AsyncWrite. So I don't think MeasLink can directly work with tokio. The `tokio-rustls` crate is what you need.
