### ISSUE TITLE
Proxy Server Support

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [mesalock-linux/mesalink#34]
Is mesalink in a place where it could be used in a proxy server like nginx or caddy?

**Comment by ymjing** [comment]
We haven't tried using MesaLink with Nginx; but it's worth trying. 
Caddy uses gotls rather than OpenSSL via FFI; that's another story.

**Comment by Th3Whit3Wolf** [comment]
Is there any other proxy server you have used Mesalink with? Mesalink/Rustls seems like the most ideal TLS Protocol to use for a proxy server.

**Comment by ymjing** [comment]
@Th3Whit3Wolf Try https://github.com/sozu-proxy/sozu ?
