### ISSUE TITLE
Will PKCS#11 be supported?

### ISSUE THREAD

**Issue by ghost** [mesalock-linux/mesalink#37]
Do you plan supporting pkcs#11 in the future to utilize HSMs?

**Comment by ymjing** [comment]
Haven't thought about this yet. What OpenSSL APIs would be needed to support HSMs?

**Comment by ghost** [comment]
Openssl has engine api to load pkcs11 engine. [libp11](https://github.com/OpenSC/libp11) is widely used.

**Comment by ymjing** [comment]
We are refactoring MesaLink at this moment. Generally, we don't want a dynamically loaded shared lib to undermine the memory safety of MesaLink.

**Comment by ymjing** [comment]
This has been staled. Currently we have no plan or bandwidth for new features. Closing for now.
