### ISSUE TITLE
What is the different between mesalink and intel sgx secret provisioning?

### ISSUE THREAD

**Issue by m3ngzhang** [mesalock-linux/mesalink#44]
Hi, I'm a new learner of mesatee. I read something about intel sgx secret provisioning and mesalink from github and intel official guide, and that confuses me. Because I dont understand why u guys write another TLS library.  For my perspective, intel already shows us a way to send secrets into enclave, which is secret provisioning, so we should not have to make another one. Looking forward to any relay. Thx.

**Comment by mssun** [comment]
Thanks for asking. Can you provide a link to the doc you mentioned . Some docs are outdated and  some were not written clearly. I’m very glad to explain that. Thanks!

**Comment by m3ngzhang** [comment]
@mssun Think u for your reply. I appreciate!
(1) I got information of secret provisioning from intel sgx guide page 19. This is the link: https://download.01.org/intel-sgx/linux-2.2/docs/Intel_SGX_Developer_Guide.pdf
(2) I read rust sgx sdk, and I found that u guys use openssl in ue-ra sample. Here is the link: https://github.com/apache/incubator-teaclave-sgx-sdk/blob/master/samplecode/ue-ra/Readme.md
It seems that you allow us to program with openssl instead of your mesalink. Even though it is just a sample, it is still safe enough without mesalink, right?
(3) I also wanna ask what did you do to mesalink. Is mesalink a rust version openssl? If I wanna write my own program based on rust sgx sdk, should I use openssl like the sample or mesalink instead?

**Comment by dingelish** [comment]
(1) ue-ra sample does **not** include anything directly from openssl.
(2) the guide in Readme shows how to use openssl cli to generate keys/certs
(3) currently mesalink is not directly involved in rust-sgx projects
(4) mesalink is **not** a rust version of openssl. it's similar to a wrapper of [rustls](https://github.com/ctz/rustls), to help people use rustls wherever they want.
(5) if you want to use rust-sgx-sdk, please use the ported rustls directly. there is no option for openssl. you do not need mesalink in SGX projects, because you don't need to wrap rustls. you can directly use rustls (ported version)
ported rustls: https://github.com/mesalock-linux/rustls/tree/mesalock_sgx

**Comment by dingelish** [comment]
btw

in the sgx scenario, i think the transportation layer security is better than application layer security.

transportation layer security provides lots of additional security features like key rotation, management of the chain of trust, authentication and authorization, revocation, and much better compatibility. re-invent this wheel in application layer provisioning is do-able, but not a good choice. basically it needs to implement every component of ssl/tls. i don't mind if you want to do it and i'd like to merge your codes if you can finish it.

**Comment by dingelish** [comment]
i want to mention that the prototype of sgx-ra-tls was proposed and implemented by intel, to replace the old-fashioned secret provisioning. they do not want to re-invent either.

https://github.com/cloud-security-research/sgx-ra-tls
https://github.com/cloud-security-research/sgx-ra-tls/blob/master/whitepaper.pdf

**Comment by m3ngzhang** [comment]
@dingelish 
Thx again, bro. Your answer is an inspiration to me. That helps me a lot.

**Comment by mssun** [comment]
Since the question has been answered (properly), I'm closing this issue.
