### ISSUE TITLE
连接smtps要时出错

### ISSUE THREAD

**Issue by FFFF0000H** [mesalock-linux/mesalink#48]
连接smtps时出现
error:[0x3000907]:[mesalink]:[src/libssl/ssl.rs:344]:[TLSErrorAlertReceivedHandshakeFailure]

**Comment by Darkspirit** [comment]
To which smtps server have you tried to connect to? It might have an insecure configuration that is not supported.

**Comment by FFFF0000H** [comment]
> To which smtps server have you tried to connect to? It might have an insecure configuration that is not supported.
I learned from example client.c from source code. i changed host to smtp.xxx.com. then set port to 465. i could create socked and connected to server without ssl. but error occurred when ssl_connect.
with the same code i can connect to https server but smtps server.

**Comment by Darkspirit** [comment]
> smtp.xxx.com

I doubt that's the real hostname you are connecting to.(?) You could take these TLS protocol and cipherlist configurations as an example for port 465 (in Postfix' master.cf configuration file):
https://ssl-config.mozilla.org/#server=postfix&version=3.4.8&config=intermediate&openssl=1.1.1d&guideline=5.4

>  with the same code i can connect to https server but smtps server.

Yes, web servers are usually better configured than mail servers.

**Comment by FFFF0000H** [comment]
> > smtp.xxx.com
> 
> I doubt that's the real hostname you are connecting to.(?) You could take these TLS protocol and cipherlist configurations as an example for port 465 (in Postfix' master.cf configuration file):
> https://ssl-config.mozilla.org/#server=postfix&version=3.4.8&config=intermediate&openssl=1.1.1d&guideline=5.4
> 
> > with the same code i can connect to https server but smtps server.
> 
> Yes, web servers are usually better configured than mail servers.

I’ve tried  smtp-mail.outlook.com , smtp.aliyun.com and smtp.qq.com, it only worked on smtp.qq.com.
I tried with OpenSSL before, they all worked.

**Comment by Darkspirit** [comment]
* It seems [smtp-mail.outlook.com](https://discovery.cryptosense.com/analyze/smtp-mail.outlook.com/352d308) does [not](https://support.office.com/en-us/article/pop-and-imap-email-settings-for-outlook-8361e398-8af4-4e97-b147-6c6c4ac95353?omkt=en-US&ui=en-US&rs=en-US&ad=US) offer smtps on port 465. It only supports STARTTLS port 587 which first opens a plaintext SMTP connection and then requests an upgrade to TLS (which is not recommended). Fortunately they support regular TLS for imaps (port 993) and pop3s (port 995) though.
Therefore I'm not able to connect with:
`openssl s_client -connect smtp-mail.outlook.com:465`
But STARTTLS works:
`openssl s_client -connect smtp-mail.outlook.com:587 -starttls smtp`
If you manage to implement the STARTTLS upgrade mechanism, everything should work as TLS 1.2 and ECDHE-RSA-AES256-GCM-SHA384 are supported on port 587.

* smtp.aliyun.com:465 does not support modern encryption at all. It must support ECDHE ciphers like ECDHE-RSA-AES256-GCM-SHA384. Please contact their support if you are customer.
https://discovery.cryptosense.com/analyze/smtp.aliyun.com/af82cc8#host-1-port-465 > Show scan details

* [smtp.qq.com:465](https://discovery.cryptosense.com/analyze/smtp.qq.com/68208d9#host-1-port-465) supports ECDHE-RSA-AES128-GCM-SHA256. Therefore we can connect. :)

**Comment by FFFF0000H** [comment]
> * It seems [smtp-mail.outlook.com](https://discovery.cryptosense.com/analyze/smtp-mail.outlook.com/352d308) does [not](https://support.office.com/en-us/article/pop-and-imap-email-settings-for-outlook-8361e398-8af4-4e97-b147-6c6c4ac95353?omkt=en-US&ui=en-US&rs=en-US&ad=US) offer smtps on port 465. It only supports STARTTLS port 587 which first opens a plaintext SMTP connection and then requests an upgrade to TLS (which is not recommended). Fortunately they support regular TLS for imaps (port 993) and pop3s (port 995) though.
>   Therefore I'm not able to connect with:
>   `openssl s_client -connect smtp-mail.outlook.com:465`
>   But STARTTLS works:
>   `openssl s_client -connect smtp-mail.outlook.com:587 -starttls smtp`
>   If you manage to implement the STARTTLS upgrade mechanism, everything should work as TLS 1.2 and ECDHE-RSA-AES256-GCM-SHA384 are supported on port 587.
> * smtp.aliyun.com:465 does not support modern encryption at all. It must support ECDHE ciphers like ECDHE-RSA-AES256-GCM-SHA384. Please contact their support if you are customer.
>   https://discovery.cryptosense.com/analyze/smtp.aliyun.com/af82cc8#host-1-port-465 > Show scan details
> * [smtp.qq.com:465](https://discovery.cryptosense.com/analyze/smtp.qq.com/68208d9#host-1-port-465) supports ECDHE-RSA-AES128-GCM-SHA256. Therefore we can connect. :)

thanks a lot.

**Comment by Darkspirit** [comment]
Can this be closed?
