### ISSUE TITLE
can't make

### ISSUE THREAD

**Issue by z2665** [mesalock-linux/mesalink#6]
when I use make 
It show 
`cd . && \
 cargo rustc \
	--release --no-default-features --features " client_apis server_apis error_strings aesgcm chachapoly tls13 x25519 ecdh ecdsa verifier"  -- -C overflow-checks=yes -C link-args=-Wl,--gc-sections -C opt-level=z
    Updating git repository `https://github.com/mesalock-linux/rustls`
error: failed to load source for a dependency on `rustls`                       

Caused by:
  Unable to update https://github.com/mesalock-linux/rustls?branch=mesalink#12dd7e88

Caused by:
  revspec '12dd7e883e3c5a8ca782ff90e2046ae760e39161' not found; class=Reference (4); code=NotFound (-3)`

Is network error?

**Comment by fneddy** [comment]
same for me. It is because of  [Cargo.lock#L254](https://github.com/mesalock-linux/mesalink/blob/develop/Cargo.lock#L254) wich points to a non existing commit.

**Comment by ymjing** [comment]
Sounds weird to me. A clean clone of the master branch on my machine can build. And the latest CI build passed without any problem. As the maintainer of MesaLock Linux suggested, it could be the *wall*. Please try again on a clean clone from the master branch. If it still does not work, you may want a global proxy for Github. Let me know if this solves the problem.

**Comment by z2665** [comment]
@kevinis I set  global git config  use http.proxy=socks5://127.0.0.1:1080 and https.proxy=socks5://127.0.0.1:1080 .Then it will use shadowsocks proxy to HongKong.  Then I  Updating git repository very quickly.But  I also get the error revspec `'12dd7e883e3c5a8ca782ff90e2046ae760e39161' not found; class=Reference (4); code=NotFound (-3)`

**Comment by ymjing** [comment]
Looks like it is the outdated Cargo.lock. Could you please clone the latest `develop` branch and try it again?

**Comment by z2665** [comment]
@kevinis  Thanks.  I checkout the develop branch. It work well.

**Comment by ymjing** [comment]
Cool. The CI also passed. We have updated the `master` branch to fix the outdated Cargo.lock problem.
