### ISSUE TITLE
support Freebsd

### ISSUE THREAD

**Issue by fneddy** [mesalock-linux/mesalink#7]
Hello,

i tried mesalink on freebsd. the only thing that needs to change is to [include `netinet/in.h` in server.c](https://github.com/fneddy/mesalink/commit/2931fefd16a8de45391aa74dae45f34b3372d30f#diff-201a10d0b5b05127374f83e9fcd1f593R18). 

This does not break compile on linux, through I dont know about Mac.
If wanted I'll create a pull request.

**Comment by ymjing** [comment]
Good to know MesaLink also works on freebsd. Please feel free to submit your PR.

**Comment by fneddy** [comment]
done #8

**Comment by ymjing** [comment]
Will merge the PR once we have fully test MesaLink on FreeBSD.

**Comment by ymjing** [comment]
As we have few FreeBSD users, this feature is not considered for now.
