### ISSUE TITLE
I have a problem for help.

### ISSUE THREAD

**Issue by jnchzy** [mesalock-linux/mesalink#9]
In the examples directionary, there is a client program. When I compile the client program, the follows result is shown:
![tim 20180411161005](https://user-images.githubusercontent.com/20393374/38604433-efee3a54-3da2-11e8-88a8-10da5f9c41c0.jpg)
I don't know the reason, can you give me some help? Thank you very much!

**Comment by fneddy** [comment]
If you want to build the examples you need to activate this. 

    autogen.sh  - - enable-examples
    make

**Comment by ymjing** [comment]
@fneddy is correct. By default the examples are not built together with the library.

Once the MesaLink library is installed, you can compile the example and link the executable to MesaLink, for example:
```shell
$ sudo make install
$ cd examples/client
$ gcc -o client client.c -lmesalink
```
